steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - europe-west6-docker.pkg.dev/$PROJECT_ID/foodbot/foodbot:$COMMIT_SHA
      - .

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - europe-west6-docker.pkg.dev/$PROJECT_ID/foodbot/foodbot:$COMMIT_SHA
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - foodbot
      - --image=europe-west6-docker.pkg.dev/$PROJECT_ID/foodbot/foodbot:$COMMIT_SHA
      - --region=europe-west6
      - --allow-unauthenticated
      - --port=8080
      - --set-secrets=TELEGRAM_API_KEY=TELEGRAM_API_KEY:latest
      - --set-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest
      - --set-secrets=GITHUB_TOKEN=GITHUB_TOKEN:latest
      - --set-secrets=TELEGRAM_WEBHOOK_SECRET=TELEGRAM_WEBHOOK_SECRET:latest
      - --set-secrets=GOOGLE_CRED_JSON=GOOGLE_CRED_JSON:latest
      # Beim 2. Deploy PUBLIC_URL setzen (s.u.)
      # - --set-env-vars=PUBLIC_URL=https://<CloudRun-URL>

images:
  - europe-west6-docker.pkg.dev/$PROJECT_ID/foodbot/foodbot:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
