options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1) Build
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - europe-west6-docker.pkg.dev/foodapp-463218/foodbot/foodbot:$COMMIT_SHA
      - .

  # 2) Push
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - europe-west6-docker.pkg.dev/foodapp-463218/foodbot/foodbot:$COMMIT_SHA

  # 3) (optional) kurzer Check, dass wichtige Pakete im Image sind
  - id: verify-deps-inside-image
    name: gcr.io/cloud-builders/docker
    args:
      - run
      - --rm
      - europe-west6-docker.pkg.dev/foodapp-463218/foodbot/foodbot:$COMMIT_SHA
      - python
      - -c
      - |
        import importlib.metadata as md
        import telegram, telegram.ext, tornado
        print("PTB =", md.version('python-telegram-bot'))
        print("tornado =", md.version('tornado'))
        print("IMAGE DEPS OK")

  # 4) Deploy (einfach & robust)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - foodbot
      - --image=europe-west6-docker.pkg.dev/foodapp-463218/foodbot/foodbot:$COMMIT_SHA
      - --region=europe-west6
      - --allow-unauthenticated
      - --port=8080
      - --set-secrets=TELEGRAM_API_KEY=TELEGRAM_API_KEY:latest
      - --set-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest
      - --set-secrets=GITHUB_TOKEN=GITHUB_TOKEN:latest
      - --set-secrets=TELEGRAM_WEBHOOK_SECRET=TELEGRAM_WEBHOOK_SECRET:latest
      - --set-secrets=GOOGLE_CRED_JSON=GOOGLE_CRED_JSON:latest
      - --set-env-vars=PUBLIC_URL=https://foodbot-1055976146993.europe-west6.run.app,BASE_URL=https://foodbot-1055976146993.europe-west6.run.app,ROLL_OUT=$COMMIT_SHA

images:
  - europe-west6-docker.pkg.dev/foodapp-463218/foodbot/foodbot:$COMMIT_SHA
