# Blue/Green mit tag-basiertem Health-Check (cand) und hartem 100%-Switch
options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE
timeout: "1800s"

steps:
  # 1) Build & Push
  - id: build image
    name: gcr.io/cloud-builders/docker
    args: ["build","-t","europe-west6-docker.pkg.dev/$PROJECT_ID/foodbot/foodbot:$COMMIT_SHA","."]

  - id: push image
    name: gcr.io/cloud-builders/docker
    args: ["push","europe-west6-docker.pkg.dev/$PROJECT_ID/foodbot/foodbot:$COMMIT_SHA"]

  # 2) Deploy (0%) und Tagging vorbereiten
  - id: deploy 0% (no-traffic)
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -ceu
      - |
        set -o pipefail
        region="europe-west6"
        service="foodbot"
        img="europe-west6-docker.pkg.dev/$PROJECT_ID/foodbot/foodbot:$COMMIT_SHA"

        echo "→ deploy ${service} (${region}) image ${img} (no-traffic)"
        gcloud run deploy "${service}" \
          --region="${region}" \
          --image="${img}" \
          --no-traffic \
          --port=8080 \
          --allow-unauthenticated \
          --set-secrets=TELEGRAM_API_KEY=TELEGRAM_API_KEY:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,GITHUB_TOKEN=GITHUB_TOKEN:latest,TELEGRAM_WEBHOOK_SECRET=TELEGRAM_WEBHOOK_SECRET:latest,GOOGLE_CRED_JSON=GOOGLE_CRED_JSON:latest

        cand="$(gcloud run services describe "${service}" --region "${region}" --format='value(status.latestCreatedRevisionName)')"
        live="$(gcloud run services describe "${service}" --region "${region}" --format='value(status.latestReadyRevisionName)')"
        echo "candidate=${cand}"
        echo "live=${live}"
        test -n "${cand}" || { echo "❌ no candidate revision"; exit 10; }

        # Tag 'cand' an Kandidat bei 0% hängen (Traffic der Live-Revision bleibt 100%)
        if [ -n "${live}" ] && [ "${live}" != "${cand}" ]; then
          echo "→ set live=100%, cand=0% and tag cand"
          gcloud run services update-traffic "${service}" --region "${region}" \
            --to-revisions "${live}=100,${cand}=0" \
            --tag "${cand}=cand"
        else
          echo "→ only one revision or same as live; add tag on candidate"
          gcloud run services update-traffic "${service}" --region "${region}" \
            --add-tag "${cand}=cand"
        fi

        printf '%s' "${cand}" > /workspace/cand.txt

  # 3) Ready → Health → Traffic=100
  - id: ready + health + traffic
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -ceu
      - |
        set -o pipefail
        region="europe-west6"
        service="foodbot"
        cand="$(cat /workspace/cand.txt)"
        echo "track candidate: ${cand}"

        json_get() {
          python3 - "$1" << 'PY'
import sys, json
field=sys.argv[1]
d=json.load(sys.stdin)
conds=d.get("status",{}).get("conditions",[])
def pick(t,k):
  for c in conds:
    if c.get("type")==t: return c.get(k,"") or ""
  return ""
if field=="ready.status":  print(pick("Ready","status"))
elif field=="ready.reason":print(pick("Ready","reason"))
elif field=="active.status":print(pick("Active","status"))
elif field=="url":         print(d.get("status",{}).get("url","") or d.get("status",{}).get("address",{}).get("url",""))
PY
        }

        dump_logs() {
          echo "== recent logs for ${cand} =="
          gcloud logging read \
            "resource.type=cloud_run_revision AND resource.labels.service_name=${service} AND resource.labels.revision_name=${cand}" \
            --limit=200 --order=desc --format='value(textPayload)' || true
        }
        trap 'dump_logs' ERR

        # Parallel-Deploy verhindern
        for i in $(seq 1 80); do
          latest="$(gcloud run services describe "${service}" --region "${region}" --format='value(status.latestCreatedRevisionName)')"
          if [ -n "${latest}" ] && [ "${latest}" != "${cand}" ]; then
            echo "❌ parallel deploy detected: latest=${latest} expected=${cand}"
            exit 24
          fi

          js="$(gcloud run revisions describe "${cand}" --region "${region}" --format=json || true)"
          ready="$(printf '%s' "${js}" | json_get ready.status | tr -d '\r')"
          rreason="$(printf '%s' "${js}" | json_get ready.reason | tr -d '\r')"
          astatus="$(printf '%s' "${js}" | json_get active.status | tr -d '\r')"

          printf '  [%02d/80] Ready=%s  ReadyReason=%s  Active=%s\n' "$i" "${ready:-?}" "${rreason:--}" "${astatus:--}"

          [ "${rreason:-}" = "HealthCheckContainerError" ] && { echo "❌ HealthCheckContainerError"; exit 20; }
          [ "${ready}" = "True" ] && break
          sleep 6
        done
        [ "${ready}" = "True" ] || { echo "❌ Ready not reached"; exit 21; }

        # cand-URL (tag) bestimmen
        svc_url="$(gcloud run services describe "${service}" --region "${region}" --format='value(status.url)')"
        host="${svc_url#https://}"
        cand_url="https://cand---${host}"
        echo "🩺 GET ${cand_url%/}/webhook/health"
        code="$(curl -sS -o /dev/null -w '%{http_code}' --max-time 15 "${cand_url%/}/webhook/health" || echo 000)"
        echo "→ HTTP ${code}"
        [ "${code}" = "200" ] || { echo "❌ health != 200"; exit 22; }

        echo "🔁 traffic → ${cand}=100"
        gcloud run services update-traffic "${service}" --region "${region}" --to-revisions "${cand}=100"
        echo "✅ Traffic 100% auf ${cand}"

images:
  - europe-west6-docker.pkg.dev/$PROJECT_ID/foodbot/foodbot:$COMMIT_SHA
