substitutions:
  _REGION: europe-west6
  _AR_REPO: foodbot
  _SERVICE: foodbot
  _IMAGE: europe-west6-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','${_IMAGE}','.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','${_IMAGE}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_IMAGE}
      - --region=${_REGION}
      - --allow-unauthenticated
      - --port=8080
      - --set-secrets=TELEGRAM_API_KEY=TELEGRAM_API_KEY:latest
      - --set-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest
      - --set-secrets=GITHUB_TOKEN=GITHUB_TOKEN:latest
      - --set-secrets=TELEGRAM_WEBHOOK_SECRET=TELEGRAM_WEBHOOK_SECRET:latest
      - --set-secrets=GOOGLE_CRED_JSON=GOOGLE_CRED_JSON:latest
      # PUBLIC_URL setzen wir nach dem ersten Deploy:
      # - --set-env-vars=PUBLIC_URL=https://<CloudRun-URL>

images:
  - ${_IMAGE}

logging: CLOUD_LOGGING_ONLY
